name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        
    - name: Install system dependencies
      shell: powershell
      run: |
        # Install Visual C++ Redistributable if needed
        choco install vcredist2015 -y
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pyinstaller==5.13.0
        pip install PyQt5==5.15.9 python-twain==1.0.4 pillow==10.0.0 pywin32==306
        pip install pyqt5-tools  # Additional Qt tools
        
    - name: Verify environment
      run: |
        python --version
        pip list
        pyinstaller --version
        
    - name: Build with PyInstaller (with debug)
      run: |
        pyinstaller --noconfirm --clean --onefile --windowed ^
          --name DocumentScanner ^
          --hidden-import='PyQt5.QtCore' ^
          --hidden-import='PyQt5.QtGui' ^
          --hidden-import='PyQt5.QtWidgets' ^
          --hidden-import='PIL._tkinter_finder' ^
          --hidden-import='sane' ^
          --hidden-import='twain' ^
          --log-level DEBUG ^
          scanner_app.py 2>&1 | tee build.log
        
    - name: Show build log
      if: always()
      run: type build.log
        
    - name: Upload executable
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: DocumentScanner
        path: dist/DocumentScanner.exe
        retention-days: 5
        
    - name: Upload debug info
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Build-Debug-Info
        path: |
          build.log
          build/
          dist/
